
package jaxwsGenerated;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GCDService", targetNamespace = "http://jaxws.services.java.main", wsdlLocation = "file:/C:/Users/barani/IdeaProjects/GCD_MQ/src/main/resources/wsdl/GCDService.wsdl")
public class GCDService_Service
    extends Service
{

    private final static URL GCDSERVICE_WSDL_LOCATION;
    private final static WebServiceException GCDSERVICE_EXCEPTION;
    private final static QName GCDSERVICE_QNAME = new QName("http://jaxws.services.java.main", "GCDService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/barani/IdeaProjects/GCD_MQ/src/main/resources/wsdl/GCDService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GCDSERVICE_WSDL_LOCATION = url;
        GCDSERVICE_EXCEPTION = e;
    }

    public GCDService_Service() {
        super(__getWsdlLocation(), GCDSERVICE_QNAME);
    }

    public GCDService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GCDSERVICE_QNAME, features);
    }

    public GCDService_Service(URL wsdlLocation) {
        super(wsdlLocation, GCDSERVICE_QNAME);
    }

    public GCDService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GCDSERVICE_QNAME, features);
    }

    public GCDService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GCDService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GCDService
     */
    @WebEndpoint(name = "GCDService")
    public GCDService getGCDService() {
        return super.getPort(new QName("http://jaxws.services.java.main", "GCDService"), GCDService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GCDService
     */
    @WebEndpoint(name = "GCDService")
    public GCDService getGCDService(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.services.java.main", "GCDService"), GCDService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GCDSERVICE_EXCEPTION!= null) {
            throw GCDSERVICE_EXCEPTION;
        }
        return GCDSERVICE_WSDL_LOCATION;
    }

}
