
package jaxwsGenerated;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GCDService", targetNamespace = "http://jaxws.services.java.main/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GCDService {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gcdSum", targetNamespace = "http://jaxws.services.java.main/", className = "jaxwsGenerated.GcdSum")
    @ResponseWrapper(localName = "gcdSumResponse", targetNamespace = "http://jaxws.services.java.main/", className = "jaxwsGenerated.GcdSumResponse")
    @Action(input = "http://jaxws.services.java.main/GCDService/gcdSumRequest", output = "http://jaxws.services.java.main/GCDService/gcdSumResponse")
    public int gcdSum();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gcdList", targetNamespace = "http://jaxws.services.java.main/", className = "jaxwsGenerated.GcdList")
    @ResponseWrapper(localName = "gcdListResponse", targetNamespace = "http://jaxws.services.java.main/", className = "jaxwsGenerated.GcdListResponse")
    @Action(input = "http://jaxws.services.java.main/GCDService/gcdListRequest", output = "http://jaxws.services.java.main/GCDService/gcdListResponse")
    public List<String> gcdList();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gcd", targetNamespace = "http://jaxws.services.java.main/", className = "jaxwsGenerated.Gcd")
    @ResponseWrapper(localName = "gcdResponse", targetNamespace = "http://jaxws.services.java.main/", className = "jaxwsGenerated.GcdResponse")
    @Action(input = "http://jaxws.services.java.main/GCDService/gcdRequest", output = "http://jaxws.services.java.main/GCDService/gcdResponse")
    public int gcd();

}
